CREATE TABLE CPU (
  CPUId NUMBER PRIMARY KEY NOT NULL,
  CPUName VARCHAR2(100) NOT NULL,
  socketId NUMBER NOT NULL,
  brandId NUMBER NOT NULL,
  CPUSpeedMHZ NUMBER NOT NULL,
  coreCnt NUMBER NOT NULL,
  threadCnt NUMBER NOT NULL,
  wattage NUMBER NOT NULL
);

CREATE TABLE CPUCooler (
  CPUCoolerId NUMBER PRIMARY KEY NOT NULL,
  CPUCoolerName VARCHAR2(100) NOT NULL,
  socketId NUMBER NOT NULL
);

CREATE TABLE CPURAMComp (
  CompId NUMBER PRIMARY KEY NOT NULL,
  CPUId NUMBER NOT NULL,
  RAMTypeId NUMBER NOT NULL,
  SpeedMHZ NUMBER NOT NULL
);

CREATE TABLE Sockets (
  SocketId NUMBER PRIMARY KEY NOT NULL,
  socketName VARCHAR2(20)
);

CREATE TABLE Mobo (
  MoboId NUMBER PRIMARY KEY NOT NULL,
  MoboName VARCHAR2(255) NOT NULL,
  socketId NUMBER NOT NULL,
  formId NUMBER NOT NULL,
  brandId NUMBER NOT NULL,
  supportedRAMTypeId NUMBER NOT NULL,
  RAMSlotCount NUMBER NOT NULL
);

CREATE TABLE MoboPCI (
  MoboId NUMBER NOT NULL,
  PCIId NUMBER NOT NULL
);

CREATE TABLE PCI (
  PCIId NUMBER PRIMARY KEY NOT NULL,
  version NUMBER NOT NULL,
  width NUMBER NOT NULL
);

CREATE TABLE Brands (
  brandId NUMBER PRIMARY KEY NOT NULL,
  brandName VARCHAR2(100) NOT NULL
);

CREATE TABLE RAM (
  RAMId NUMBER PRIMARY KEY NOT NULL,
  RAMName VARCHAR2(255) NOT NULL,
  RAMTypeId NUMBER NOT NULL,
  brandId NUMBER NOT NULL,
  RAMSizeGB NUMBER NOT NULL,
  RAMSpeedMHZ NUMBER NOT NULL,
  stickCount NUMBER NOT NULL
);

CREATE TABLE RAMType (
  RAMTypeId NUMBER PRIMARY KEY NOT NULL,
  RAMTypeName VARCHAR2(20) NOT NULL
);

CREATE TABLE GPU (
  GPUId NUMBER PRIMARY KEY NOT NULL,
  GPUName VARCHAR2(255) NOT NULL,
  brandId NUMBER NOT NULL,
  GPUSpeedMHZ NUMBER NOT NULL,
  GPURAMSizeGB NUMBER NOT NULL,
  PCIPortId NUMBER NOT NULL,
  wattage NUMBER NOT NULL
);

CREATE TABLE FormFactor (
  formId NUMBER PRIMARY KEY NOT NULL,
  formName VARCHAR2(20) NOT NULL,
  widthMM NUMBER NOT NULL,
  heightMM NUMBER NOT NULL
);

CREATE TABLE PCCase (
  CaseId NUMBER PRIMARY KEY NOT NULL,
  CaseName VARCHAR2(255) NOT NULL,
  formId NUMBER NOT NULL,
  brandId NUMBER NOT NULL
);

CREATE TABLE PSU (
  PSUId NUMBER PRIMARY KEY NOT NULL,
  PSUName VARCHAR2(255) NOT NULL,
  wattage NUMBER NOT NULL,
  quality NUMBER NOT NULL,
  brandId NUMBER NOT NULL
);

CREATE TABLE PSUQuality (
  PSUQualityId NUMBER PRIMARY KEY NOT NULL,
  qualityName VARCHAR2(50) NOT NULL,
  efficiency NUMBER NOT NULL
);

CREATE TABLE Users (
  userId NUMBER PRIMARY KEY NOT NULL,
  userName VARCHAR2(255) NOT NULL,
  password VARCHAR2(255) NOT NULL,
  regDate  DATE DEFAULT SYSDATE
);

CREATE TABLE UserLog (
  logId NUMBER PRIMARY KEY NOT NULL,
  action VARCHAR2(10) NOT NULL,
  actionTimestamp TIMESTAMP DEFAULT SYSTIMESTAMP,
  newUserName VARCHAR2(255),
  newPassword VARCHAR2(255),
  oldUserName VARCHAR2(255),
  oldPassword VARCHAR2(255),
  performedBy VARCHAR2(255) DEFAULT USER
);

CREATE TABLE Builds (
  buildId NUMBER PRIMARY KEY NOT NULL,
  buildName VARCHAR2(255) NOT NULL,
  cpu NUMBER NOT NULL,
  pccase NUMBER NOT NULL,
  psu NUMBER NOT NULL,
  cpuCooler NUMBER NOT NULL,
  mobo NUMBER NOT NULL,
  gpu NUMBER NOT NULL,
  ram NUMBER NOT NULL,
  wattage NUMBER NOT NULL
);

CREATE TABLE SavedBuilds (
  userId NUMBER NOT NULL,
  buildId NUMBER NOT NULL
);

CREATE TABLE Supplier (
  supplierId NUMBER PRIMARY KEY NOT NULL,
  supplierName VARCHAR2(255) NOT NULL
);

CREATE TABLE ProductType (
  productTypeId NUMBER PRIMARY KEY NOT NULL,
  productName VARCHAR2(50) NOT NULL
);

CREATE TABLE Supply (
  supplierId NUMBER NOT NULL,
  productTypeId NUMBER NOT NULL,
  productId NUMBER NOT NULL,
  price NUMBER NOT NULL
);