SET SERVEROUTPUT ON;

CREATE USER ADMIN
  IDENTIFIED BY 12345678
  DEFAULT TABLESPACE USERS
  QUOTA UNLIMITED ON USERS;

GRANT CREATE SESSION TO ADMIN;

GRANT CREATE TABLE TO ADMIN;

GRANT CREATE VIEW TO ADMIN;

GRANT CREATE SEQUENCE TO ADMIN;

GRANT CREATE PROCEDURE TO ADMIN;

GRANT CREATE TYPE TO ADMIN;

GRANT CREATE TRIGGER TO ADMIN;

GRANT EXECUTE ON DBMS_CRYPTO TO ADMIN;

ALTER SESSION SET CURRENT_SCHEMA=ADMIN;